### ISSUE TITLE
Where does reb_old.bin come from?

### ISSUE THREAD

**Issue by max1220** [vifino/lua-cpuemus#2]
In `test/zpu/` there is the file `reb_old.bin`. It is the compiled binary for a BASIC interpreter, compiled for the ZPU.

Where is that originating from? I'm just curious, but I've not found a license, and I'd like to know how it was compiled as well.

**Comment by max1220** [comment]
I (probably) found it! It's public domain:

https://github.com/20kdc/REB

**Comment by vifino** [comment]
Hey, yeah, that's exactly it.
